const menuActionTypes = {
    RETRIEVED_MENU: "RETRIEVED_MENU",
    UPDATE_MENUITEM: "UPDATE_MENUITEM",
    DELETE_MENUITEM: "DELETE_MENUITEM",
    CHANGE_FIELD_VALUE: "CHANGE_FIELD_VALUE"
};
export default menuActionTypes;
